# Configuração de patrocínio/doações
# Descomente e preencha com suas informações

# github: [yourusername]
# patreon: yourusername
# ko_fi: yourusername
# custom: ['https://your-website.com/donate']
